### ISSUE TITLE
Fails to work with cgroupv2 / unified hierarchy

### ISSUE THREAD

**Issue by mbiebl** [lxc/lxc#3183]
This is from the downstream bug report at
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944389

Package: lxc
Version: 1:3.1.0+really3.0.4-2
Severity: important
User: pkg-systemd-maintainers@lists.alioth.debian.org
Usertags: cgroupv2

Hi,

starting with systemd v243, the new upstream default in systemd will be
to use the unified hierarchy, i.e. cgroupv2

When trying to start an lxc container while booted with unified
hierarchy, I get the following failure:

lxc-start: autopkgtest-sid: lxccontainer.c: wait_on_daemonized_start: 850 Received container state "ABORTING" instead of "RUNNING"
lxc-start: autopkgtest-sid: tools/lxc_start.c: main: 329 The container failed to start
lxc-start: autopkgtest-sid: tools/lxc_start.c: main: 332 To get more details, run the container in foreground mode
lxc-start: autopkgtest-sid: tools/lxc_start.c: main: 334 Additional information can be obtained by setting the --logfile and --logpriority options

A full DEBUG log is attached.

If you want to reproduce the failure, you can boot with systemd adding
"systemd.unified_cgroup_hierarchy=true" to the kernel command line.

While the Debian package will revert back to the hybrid hierarchy for
the time being, we plan to make cgroupv2 the default in bullseye.
Once we make this switch, this bug report would become RC.

See also
https://fedoraproject.org/wiki/Changes/CGroupsV2
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=943981

[lxc.txt](https://github.com/lxc/lxc/files/3829172/lxc.txt)

**Comment by emojifreak** [comment]
I observed the same issue with yesterday's build of lxc from https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/daily

```
# dpkg-query -W lxc
lxc	3.2.1+master~20191129-1942-0ubuntu1~disco
```

The relevant error message was

```
lxc-start my-container 20191130121103.128 WARN     cgfsng - cgroups/cgfsng.c:get_hierarchy:208 - There is no useable devices controller
lxc-start my-container 20191130121103.128 ERROR    cgfsng - cgroups/cgfsng.c:cg_legacy_set_data:2425 - Failed to setup limits for the "devices" controller. The controller seems to be unused by "cgfsng" cgroup driver or not enabled on the cgroup hierarchy
lxc-start my-container 20191130121103.128 WARN     cgfsng - cgroups/cgfsng.c:__cg_legacy_setup_limits:2465 - Failed to set "devices.deny" to "a"
lxc-start my-container 20191130121103.128 ERROR    start - start.c:lxc_spawn:1910 - Failed to setup legacy device cgroup controller limits
```

**Comment by thmo** [comment]
See also #2597.Furthermore

**Comment by emojifreak** [comment]
As advised in https://github.com/lxc/lxc/issues/2268#issuecomment-380019126
this problem seems to be worked around by adding

```
lxc.cgroup.devices.allow =
lxc.cgroup.devices.deny =
```

**Comment by brauner** [comment]
On a pure unified system cgroup v1 device restrictions will not work. So keys like `lxc.cgroup.devices.{allow,deny}` will not work.

Note that with current master you can set:
`lxc.cgroup2.devices.{deny,allow}`
to use the `ebpf` based device controller with the exact same semantics as on the v1 devices controller just that LXC - if real root is available at container startup.

Once @stgraber merges https://github.com/lxc/lxc/pull/3195 live-update for the `ebpf` based device controller will also work.

**Comment by emojifreak** [comment]
Even with the workaround `lxc.cgroup.devices.allow =` and `lxc.cgroup.devices.deny =`, guest ubuntu/eoan/amd64 made by `lxc-create` fails to start with error messages

```
Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
[!!!!!!] Failed to mount API filesystems.
Exiting PID 1...
```

In addition, the above problem is not solved even with `lxc.init.cmd = /lib/systemd/systemd systemd.unified_cgroup_hierarchy` as advised in https://github.com/lxc/lxc/issues/2991#issuecomment-551897938

On the other hand, guest ubuntu/**trusty**/amd64, which uses the old `upstart` and does not use `systemd`, starts without any problem, with  `lxc.cgroup.devices.allow =` and `lxc.cgroup.devices.deny =`. Even after this issue is resolved in the latest commits, there probably remains an incompatibility between the host lxc and the guest systemd.

I observed the above behavior with the host systemd with `systemd.unified_cgroup_hierarchy=1` and lxc version below:

```dpkg-query -W | grep lxc
liblxc-common	3.2.1+master~20191121-0030-0ubuntu1~eoan
liblxc1	3.2.1+master~20191121-0030-0ubuntu1~eoan
lxc	3.2.1+master~20191121-0030-0ubuntu1~eoan
lxc-utils	3.2.1+master~20191121-0030-0ubuntu1~eoan
```

**Comment by brauner** [comment]
@emojifreak try also with:
`
lxc.mount.auto = cgroup:rw:force
`

It might be that systemd inside the container can't mount `cgroup2` so forcing it to be pre-mounted should work.

**Comment by emojifreak** [comment]
@brauner Thank you! IT WORKED!

Actually, as `/usr/share/lxc/common.conf` has other automount items, I added
`lxc.mount.auto = proc:mixed sys:mixed cgroup:rw:force`, and I did not need `lxc.init.cmd`.

In the container, I observe
`cgroup /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0`
in `/proc/mounts`, which is as expected.

From the host's viewpoint, container's cgroups are directly made at the root
```
# ls -d /sys/fs/cgroup/lxc.*
/sys/fs/cgroup/lxc.monitor  /sys/fs/cgroup/lxc.pivot
/sys/fs/cgroup/lxc.payload
```
 which violates what the systemd maintainers say at https://github.com/systemd/systemd/blob/master/docs/CGROUP_DELEGATION.md#some-donts
though I am unsure if anyone has obligation to follow what they tell...

**Comment by brauner** [comment]
@emojifreak, if you have something that delegates cgroups to you then you can set:
`
lxc.cgroup.relative = 1
`
This will cause `lxc` to not escape to the root cgroup.
We only escape to the root cgroup to not break existing users without them expecting it.

**Comment by brauner** [comment]
> @emojifreak, if you have something that delegates cgroups to you then you can set:
> `lxc.cgroup.relative = 1`
> This will cause `lxc` to not escape to the root cgroup.

Meaning that `lxc` will assume that the cgroup it is currently in is a delegation boundary and it will create subcgroups for itself and containers in there.

**Comment by emojifreak** [comment]
`lxc.mount.auto = cgroup:rw:force` does not allow systemd in the container to start, with LXC 3.0.4 LTS running on Ubuntu 19.10 Eoan booted with systemd.unified_cgroup_hierarchy. The reason is as follows. With

```config
lxc.cgroup.devices.allow =
lxc.cgroup.devices.deny =
lxc.mount.auto = proc:mixed sys:mixed cgroup:rw:force
lxc.init.cmd = /bin/bash
```

I can use bash and see `/proc/mounts` inside the container, which has
`cgroup /sys/fs/cgroup/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0`
which results in `/sys/fs/cgroup/cgroup` in the container. Because of the incorrect location of the cgroup fs, the systemd in the container aborts with

```text
Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
[!!!!!!] Failed to mount API filesystems.
Exiting PID 1...
```

Is there any plan to fix the above issue in 3.0.4 LTS?? I observed the above issue with

```
$ dpkg-query -W | grep lxc
liblxc-common	3.0.4-0ubuntu1
liblxc1	3.0.4-0ubuntu1
lxc	3.0.4-0ubuntu1
lxc-templates	3.0.4-1ubuntu1
lxc-utils	3.0.4-0ubuntu1
```

**Comment by brauner** [comment]
@emojifreak hm yeah, we should fix this in the next bugfix release.

**Comment by brauner** [comment]
@emojifreak the fix is now in the `stable-3.0` branch and will be included in the next lts release.

**Comment by emojifreak** [comment]
@brauner Thank you very much for your quick response!
By the way, I always see `ERROR    conf - conf.c:lxc_setup_boot_id:3528 - Permission denied - Failed to mount /dev/.lxc-boot-id to /proc/sys/kernel/random/boot_id` in the log file when host Linux is booted with unified CGroup hierarchy, both in 3.0.4 and (almost) latest master branch. Is it expected?

When host Linux is booted in unified CGroup hierarchy, a user has to add some config items. Is it convenient to include such ones as a single file? For example, for the 3.0 LTS

```
# When host Linux is booted with systemd.unified_cgroup_hierarchy or
# defaulted to use the unfied CGroup hierarchy (aka CGroup V2),
# include this file after common.conf

# We must turn off the CGroup V1 device controls so that LXC can start
lxc.cgroup.devices.deny =
lxc.cgroup.devices.allow =

# If /sbin/init in guest is systemd, it requires LXC to prepare /sys/fs/cgroup
lxc.mount.auto = cgroup:rw:force
```

For the 3.2 stable (tested with `3.2.1+master~20191202-0205-0ubuntu1~eoan`)

```
# When host Linux is booted with systemd.unified_cgroup_hierarchy or
# defaulted to use the unfied CGroup hierarchy (aka CGroup V2),
# include this file after common.conf

# We must turn off the CGroup V1 device controls so that LXC can start
lxc.cgroup.devices.deny =
lxc.cgroup.devices.allow =

# If /sbin/init in guest is systemd, it requires LXC to prepare /sys/fs/cgroup
lxc.mount.auto = cgroup:rw:force

# systemd tells us that nothing should be made at the CGroup root
# https://github.com/systemd/systemd/blob/master/docs/CGROUP_DELEGATION.md#some-donts
# lxc.cgroup.relative = 1

# The below is copied from common.conf with lxc.cgroup replaced by lxc.cgroup2
# CGroup whitelist
lxc.cgroup2.devices.deny = a
## Allow any mknod (but not reading/writing the node)
lxc.cgroup2.devices.allow = c *:* m
lxc.cgroup2.devices.allow = b *:* m
## Allow specific devices
### /dev/null
lxc.cgroup2.devices.allow = c 1:3 rwm
### /dev/zero
lxc.cgroup2.devices.allow = c 1:5 rwm
### /dev/full
lxc.cgroup2.devices.allow = c 1:7 rwm
### /dev/tty
lxc.cgroup2.devices.allow = c 5:0 rwm
### /dev/console
lxc.cgroup2.devices.allow = c 5:1 rwm
### /dev/ptmx
lxc.cgroup2.devices.allow = c 5:2 rwm
### /dev/random
lxc.cgroup2.devices.allow = c 1:8 rwm
### /dev/urandom
lxc.cgroup2.devices.allow = c 1:9 rwm
### /dev/pts/*
lxc.cgroup2.devices.allow = c 136:* rwm
### fuse
lxc.cgroup2.devices.allow = c 10:229 rwm
```

**Comment by brauner** [comment]
Best solution would likely be a patch that adds an option to `configure.ac` like `--with-cgroup2` that can be used to compile liblxc for systems that uses `cgroup2` only. So e.g. `Fedora 31` can turn this compilation option on.

**Comment by emojifreak** [comment]
> Best solution would likely be a patch that adds an option to configure.ac like --with-cgroup2 that can be used to compile liblxc for systems that uses cgroup2 only. So e.g. Fedora 31 can turn this compilation option on.

Even some users on Fedora 31 are forced to use hybrid (or possibly legacy) CGroup hierarchy because they use some software unable to work under unified hierarchy (e.g. Docker). So LXC with `--with-cgroup2` may still need to be able to work under hybrid (and possibly legacy) hierarchy, or package maintainers of LXC may be required to provide two separate LXC packages with and without `--with-cgroup2`...

**Comment by emojifreak** [comment]
> ```
> Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
> [!!!!!!] Failed to mount API filesystems.
> Exiting PID 1...
> ```
> 
> In addition, the above problem is not solved even with `lxc.init.cmd = /lib/systemd/systemd systemd.unified_cgroup_hierarchy` as advised in [#2991 (comment)](https://github.com/lxc/lxc/issues/2991#issuecomment-551897938)

I am sorry, the above claim was incorrect. Actually, for vanilla LXC 3.0.4, addition of
```config
lxc.cgroup.devices.allow =
lxc.cgroup.devices.deny =
lxc.init.cmd = /lib/systemd/systemd systemd.unified_cgroup_hierarchy=1
```
to a container config is sufficient to allow usual start-up of a Linux distro with a recent version of systemd in an LXC container running on a Linux host booted with `systemd.unified_cgroup_hierarchy=1`.

**Comment by brauner** [comment]
We're about to release LXC 4.0 at the end of the week which comes with full cgroup2 support.

**Comment by thmo** [comment]
Some questions from a Fedora packager's perspective:

- Why are non-empty `lxc.cgroup.devices` directives fatal in a v2 environment, wouldn't it be better to (warn and) ignore them? As a packager, I want to ship a working `/usr/share/lxc/config/common.conf`, and it seems I can put v1 **or** v2 directives in there, but not both. So for Fedora31+, I'd default to the v2 directives. If the user decides to boot with v1 instead, they would have to modify the configuration themselves, right?

- The Ubuntu bionic and eoan guests only startup properly with **either** `lxc.init.cmd = /lib/systemd/systemd systemd.unified_cgroup_hierarchy=1` **or** `lxc.mount.auto = cgroup:mixed:force`. Which one is preferable? I guess I could put the latter in `/usr/share/lxc/config/common.conf`, and be on the safe side?

All-in-all, would some mechanism to detect v1 vs v2 at runtime, and depend on that for the configuration help?

**Comment by brauner** [comment]
> Some questions from a Fedora packager's perspective:

Thanks for getting in touch!

> 
> * Why are non-empty `lxc.cgroup.devices` directives fatal in a v2 environment, wouldn't it be better to (warn and) ignore them? As a packager, I want to ship a working `/usr/share/lxc/config/common.conf`, and it seems I can put v1 **or** v2 directives in there, but not both. So for Fedora31+, I'd default to the v2 directives. If the user decides to boot with v1 instead, they would have to modify the configuration themselves, right?

I think when we detect that we are running on pure cgroup2 layout we should just log a warning for any `lxc.cgroup.` directives. I thought about more clever solutions but I think that this option is the least unintuitive and cgroup2 is so different from legacy cgroup that it's fine.

> * The Ubuntu bionic and eoan guests only startup properly with **either** `lxc.init.cmd = /lib/systemd/systemd systemd.unified_cgroup_hierarchy=1` **or** `lxc.mount.auto = cgroup:mixed:force`. Which one is preferable? I guess I could put the latter in `/usr/share/lxc/config/common.conf`, and be on the safe side?

So `mixed:force` will pre-mount the unified hierarchy and thus force any systemd version that knows how to deal with it to use it. So if that works, then sure why not. Usually we have had the policy that it's the init systems job to configure cgroups and with cgroup namespaces that worked very well. But since we now have the unfortunate situation where you can have a cgroup2 only host and an init system in a container that only knows about v1 we are in a bit of a pickle.
If you can dynamically detect that systemd is going to be run in the container or you know for a fact that it will then you could also set `systemd.unified_cgroup_hierarchy`. In short, both work.

> 
> All-in-all, would some mechanism to detect v1 vs v2 at runtime, and depend on that for the configuration help?

Yeah, at least for pure v2 hosts.

**Comment by brauner** [comment]
@thmo does https://github.com/lxc/lxc/pull/3375 work for you?

**Comment by thmo** [comment]
> @thmo does #3375 work for you?

Well, sort of. Technically it seems to work.

However this means that, on a pure v2 system, with the default `config/common.conf`, no device limits are in effect. Is this intentional? Is this a security problem?

What about additionally ignoring the v2 directives on a v1 setup? The effect would be that we can have a default config file with _both_ types of directives in, and be sure that the default limits are always applied?

**Comment by thmo** [comment]
> So `mixed:force` will pre-mount the unified hierarchy and thus force any systemd version that knows how to deal with it to use it. So if that works, then sure why not. Usually we have had the policy that it's the init systems job to configure cgroups and with cgroup namespaces that worked very well. But since we now have the unfortunate situation where you can have a cgroup2 only host and an init system in a container that only knows about v1 we are in a bit of a pickle.
> If you can dynamically detect that systemd is going to be run in the container or you know for a fact that it will then you could also set `systemd.unified_cgroup_hierarchy`. In short, both work.

To be honest, I am not quite sure what to make with this answer ;)

To make it crystal-clear: The ideal goal (from a packager's POV) would be to deliver a default configuration (i.e. `/usr/share/lxc/config/common.conf`) that allows a user, _without touching the config_ to successfully run
```
$ dnf install lxc
$ lxc-create -n some_name -t download -d some_dist -r some_release
$ lxc-start -n some_name
```
for **all** currently offered download images, _regardless of whether the host uses pure v2 cgroups or not_.

Do you think this is possible to achieve?

**Comment by brauner** [comment]
Yeah, I think it's possible to achieve that. @thm, please see https://github.com/lxc/lxc/pull/3396

**Comment by thmo** [comment]
Looks good at first sight!

Now, what about the interaction with clients' systemd? Any chance to get that also working in both cases, without users' intervention?

**Comment by brauner** [comment]
I think `cgroups:mixed:force` is the way to go for now.

**Comment by thmo** [comment]
> I think `cgroups:mixed:force` is the way to go for now.

Alright, can you change `common.conf.in` accordingly? I would prefer that over a downstream patch.

**Comment by brauner** [comment]
I'm thinking about other approaches:
```
1. adding a compile time option telling lxc to always pre-mount cgroups
2. autodetecting cgroup2 only layouts and pre-mounting cgroups in this case
3. autodetecting systemd (might be weird to make lxc aware of the binary it's running) and pre-mounting if version is too old
```
any strong opinions?

**Comment by brauner** [comment]
Ok, I went with 1. defaulting to premounting.

**Comment by thmo** [comment]
As we don't know the final environment already at compile time (user can change it via kernel options), I think I would prefer option (2) or (3) over (1).

I agree that (3) seems a bit hackish, and I don't know whether there are reliable ways to do so.

Are there existing images that are known to fail with (2)?

Another idea could be a variant of option (3), that does not depend on on autodetection, but on an additional option that can be set per-image. Pre mounting would then happen when that option is set _and_ we are in a pure v2 layout.

**Comment by brauner** [comment]
> Ok, I went with 1. defaulting to premounting.

Sorry, I mistyped: option 2 is what I implemented.

**Comment by brauner** [comment]
> As we don't know the final environment already at compile time (user can change it via kernel options), I think I would prefer option (2) or (3) over (1).
> 
> I agree that (3) seems a bit hackish, and I don't know whether there are reliable ways to do so.
> 
> Are there existing images that are known to fail with (2)?
> 
> Another idea could be a variant of option (3), that does not depend on on autodetection, but on an additional option that can be set per-image. Pre mounting would then happen when that option is set _and_ we are in a pure v2 layout.

Right, per-image came to my mind too. We don't yet implement something like per-image config options, right @stgraber. I guess we could easily add it but would we be ok with that?

**Comment by brauner** [comment]
I really wish cgroups weren't such a hot mess. This is just crazy in general. The fact that hybrid layouts have been made a thing - even if cgroup2 in this case has no controllers enabled - is just insane.

**Comment by thmo** [comment]
Any possibility to get these changes into a release quite soon?

**Comment by jelmd** [comment]
We run Ubuntu 20.04.2 LTS with liblxc-common + liblxc1 + lxc + lxc-utils v4.0.2 and lxc-templates 3.0.4-3.
Unfortunately lxc still does not work:
```
lxc-start n04-01 20210227024655.216 ERROR    conf - conf.c:lxc_setup_boot_id:3249 - Permission denied - Failed to mount /dev/.lxc-boot-id to /proc/sys/kernel/random/boot_id
```

So, what is needed to get the container run?
