### ISSUE TITLE
Containers fails to start -  Failed to setup cgroup limits for container (cpu.shares)

### ISSUE THREAD

**Issue by Moodesstas** [lxc/lxc#3703]
* Distribution: CentOS 7
 * The output of
   * `lxc-start --version 
   `
`4.0.6`
   * `lxc-checkconfig`

```
Kernel configuration found at /boot/config-3.10.0-1127.19.1.el7.x86_64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Warning: newuidmap is not setuid-root
Warning: newgidmap is not setuid-root
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/devices
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/pids
/sys/fs/cgroup/memory
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/blkio
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/freezer

Cgroup v2 mount points:


Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities:

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/local/bin/lxc-checkconfig

```
   * `uname -a 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
   * `uanme -a 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
  
   * `cat /proc/self/cgroup
11:freezer:/
10:perf_event:/
9:blkio:/user.slice
8:hugetlb:/
7:memory:/user.slice
6:pids:/user.slice
5:cpuset:/
4:devices:/user.slice
3:cpuacct,cpu:/user.slice
2:net_prio,net_cls:/
1:name=systemd:/user.slice/user-0.slice/session-3505074.scope`

# Issue description
When this value added `lxc.cgroup.cpu.shares = 100 `to `lxc/containername/config` containers won't start. Error message bellow.

With other values no problems, for instance
lxc.cgroup.memory.soft_limit_in_bytes
lxc.cgroup.memory.limit_in_bytes
lxc.cgroup.memory.memsw.limit_in_bytes

# Information to attach
lxc-start -n container -k --logfile

```
lxc-start container 20210301140945.850 ERROR    cgfsng - cgroups/cgfsng.c:cg_legacy_set_data:2707 - No such file or directory - Failed to setup limits for the "cpu" controller. The controller seems to be unused by "cgfsng" cgroup driver or not enabled on the cgroup hierarchy
lxc-start container 20210301140945.850 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2756 - No such file or directory - Failed to set "cpu.shares" to "100"
lxc-start container 20210301140945.850 ERROR    start - start.c:lxc_spawn:1787 - Failed to setup cgroup limits for container "container"
lxc-start container 20210301140945.850 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:869 - Received container state "ABORTING" instead of "RUNNING"
lxc-start container 20210301140945.850 ERROR    lxc_start - tools/lxc_start.c:main:308 - The container failed to start
lxc-start container 20210301140945.850 ERROR    lxc_start - tools/lxc_start.c:main:311 - To get more details, run the container in foreground mode
lxc-start container 20210301140945.850 ERROR    lxc_start - tools/lxc_start.c:main:314 - Additional information can be obtained by setting the --logfile and --logpriority options
lxc-start container 20210301140945.850 ERROR    start - start.c:__lxc_start:2046 - Failed to spawn container "container"
```

**Comment by brauner** [comment]
This is fixed in `stable-4.0` we'll hopefully be able to make a release soon! Can you please try `stable-4.0`? Is that possible for you?

**Comment by Modestaso** [comment]
hello, you mean downgrade from `lxc-start --version 4.0.6` to `stable-4.0`  ?

**Comment by Moodesstas** [comment]
Hello, you mean downgrade  from `lxc-start --version 4.0.6` to `stable-4.0` ?

**Comment by Moodesstas** [comment]
We have found that with this value container starts  `lxc.group2.cpu.shares =`

@brauner What do you think is it a good approach ? changing to `lxc.group2.cpu.shares =` .
Regarding cpu limits, maybe by default the resources are distributed correctly to all containers? because without this limits i didn't notice increased load or something similar. 

Also strange why this directory doesn't contain folders "lxc.payload" "lxc.monitor" `/sys/fs/cgroup/cpu,cpuacct`

**Comment by brauner** [comment]
No, that won't work, since the `cpu` controller is mounted into a `cgroup v1` hierarchy. The keys to set values for such `cgroup v1` hierarchies are all prefixed with `lxc.cgroup.` whereas `cgroup v2` options are set via keys that are prefixed with `lxc.cgroup2.`.

According to your host's cgroup layout your on a pure `cgroup v1` layout, so you must use `lxc.cgroup.` keys to set values. As I said, this is fixed in master and in `stable-4.0`. We will be releasing a new stable version soon!

**Comment by Moodesstas** [comment]
Hello,
Sorry for my impatience. Maybe a new release data is known ?

**Comment by NerijusRazvodovskis** [comment]
Hello, seems like after new release issue is still persisting with `cgroup v1`

**Comment by brauner** [comment]
> Hello,
> Sorry for my impatience. Maybe a new release data is known ?

Oh sorry, I missed that ping so we've released `4.0.9` which should fix this.

**Comment by brauner** [comment]
> Hello, seems like after new release issue is still persisting with `cgroup v1`

Can you provide a trace log, please?

**Comment by NerijusRazvodovskis** [comment]
Hello, 

adding the output of `lxc-checkconfig`

```
LXC version 4.0.9
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-3.10.0-1127.19.1.el7.x86_64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Warning: newuidmap is not setuid-root
Warning: newgidmap is not setuid-root
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/blkio
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/devices
/sys/fs/cgroup/freezer
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/pids
/sys/fs/cgroup/memory

Cgroup v2 mount points:


Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities:

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/local/bin/lxc-checkconfig
```

Adding error log after adding value and starting container `lxc.cgroup.cpu.shares = 100`:

```
lxc-start 93760 20210603135733.201 ERROR    cgfsng - cgroups/cgfsng.c:__cgroup_tree_create:771 - File exists - Creating the final cgroup 10(lxc.monitor.93760) failed
lxc-start 93760 20210603135733.223 ERROR    cgfsng - cgroups/cgfsng.c:cgroup_tree_create:831 - File exists - Failed to create monitor cgroup 10(lxc.monitor.93760)
lxc-start 93760 20210603135733.351 ERROR    utils - utils.c:lxc_can_use_pidfd:1772 - Kernel does not support pidfds
lxc-start 93760 20210603135733.352 ERROR    cgfsng - cgroups/cgfsng.c:cg_legacy_set_data:2712 - No such file or directory - Failed to setup limits for the "cpu" controller. The controller seems to be unused by "cgfsng" cgroup driver or not enabled on the cgroup hierarchy
lxc-start 93760 20210603135733.353 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2761 - No such file or directory - Failed to set "cpu.shares" to "100"
lxc-start 93760 20210603135733.353 ERROR    start - start.c:lxc_spawn:1747 - Failed to setup cgroup limits for container "93760"
lxc-start 93760 20210603135733.355 ERROR    start - start.c:__lxc_start:2019 - Failed to spawn container "93760"
lxc-start 93760 20210603135733.354 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:869 - Received container state "ABORTING" instead of "RUNNING"
lxc-start 93760 20210603135733.359 ERROR    lxc_start - tools/lxc_start.c:main:308 - The container failed to start
lxc-start 93760 20210603135733.360 ERROR    lxc_start - tools/lxc_start.c:main:311 - To get more details, run the container in foreground mode
lxc-start 93760 20210603135733.360 ERROR    lxc_start - tools/lxc_start.c:main:314 - Additional information can be obtained by setting the --logfile and --logpriority options
```

**Comment by NerijusRazvodovskis** [comment]
👋🏻  

Sorry for pinging, any ideas?

**Comment by brauner** [comment]
No, pinging is totally fine. Sorry for the delayed reply.

This is weird. It seems that LXC doesn't detect your cgroup layout. Can you provide the output of `findmnt` and can you please start the container with `-l trace -o bla.log` and paste me the full output of `bla.log`, please?

**Comment by brauner** [comment]
(Sorry, accidentally closed.)

**Comment by Moodesstas** [comment]
> No, pinging is totally fine. Sorry for the delayed reply.
> 
> This is weird. It seems that LXC doesn't detect your cgroup layout. Can you provide the output of `findmnt` and can you please start the container with `-l trace -o bla.log` and paste me the full output of `bla.log`, please?

Hello @brauner 
**findmnt**
```
TARGET                                SOURCE                                       FSTYPE     OPTIONS
/                                     /dev/sda8                                    xfs        rw,relatime,attr2,inode64,noquota
├─/sys                                sysfs                                        sysfs      rw,nosuid,nodev,noexec,relatime
│ ├─/sys/kernel/security              securityfs                                   securityfs rw,nosuid,nodev,noexec,relatime
│ ├─/sys/fs/cgroup                    tmpfs                                        tmpfs      ro,nosuid,nodev,noexec,mode=755
│ │ ├─/sys/fs/cgroup/systemd          cgroup                                       cgroup     rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd
│ │ ├─/sys/fs/cgroup/freezer          cgroup                                       cgroup     rw,nosuid,nodev,noexec,relatime,freezer
│ │ ├─/sys/fs/cgroup/pids             cgroup                                       cgroup     rw,nosuid,nodev,noexec,relatime,pids
│ │ ├─/sys/fs/cgroup/net_cls,net_prio cgroup                                       cgroup     rw,nosuid,nodev,noexec,relatime,net_prio,net_cls
│ │ ├─/sys/fs/cgroup/cpu,cpuacct      cgroup                                       cgroup     rw,nosuid,nodev,noexec,relatime,cpuacct,cpu
│ │ ├─/sys/fs/cgroup/hugetlb          cgroup                                       cgroup     rw,nosuid,nodev,noexec,relatime,hugetlb
│ │ ├─/sys/fs/cgroup/cpuset           cgroup                                       cgroup     rw,nosuid,nodev,noexec,relatime,cpuset
│ │ ├─/sys/fs/cgroup/perf_event       cgroup                                       cgroup     rw,nosuid,nodev,noexec,relatime,perf_event
│ │ ├─/sys/fs/cgroup/memory           cgroup                                       cgroup     rw,nosuid,nodev,noexec,relatime,memory
│ │ ├─/sys/fs/cgroup/devices          cgroup                                       cgroup     rw,nosuid,nodev,noexec,relatime,devices
│ │ └─/sys/fs/cgroup/blkio            cgroup                                       cgroup     rw,nosuid,nodev,noexec,relatime,blkio
│ ├─/sys/fs/pstore                    pstore                                       pstore     rw,nosuid,nodev,noexec,relatime
│ ├─/sys/firmware/efi/efivars         efivarfs                                     efivarfs   rw,nosuid,nodev,noexec,relatime
│ ├─/sys/kernel/config                configfs                                     configfs   rw,relatime
│ └─/sys/kernel/debug                 debugfs                                      debugfs    rw,relatime
├─/proc                               proc                                         proc       rw,relatime,hidepid=2
│ ├─/proc/sys/fs/binfmt_misc          systemd-1                                    autofs     rw,relatime,fd=31,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=19608
│ └─/proc/fs/nfsd                     nfsd                                         nfsd       rw,relatime
├─/dev                                devtmpfs                                     devtmpfs   rw,nosuid,size=131917356k,nr_inodes=32979339,mode=755
│ ├─/dev/mqueue                       mqueue                                       mqueue     rw,relatime
│ ├─/dev/shm                          tmpfs                                        tmpfs      rw,nosuid,nodev
│ ├─/dev/pts                          devpts                                       devpts     rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000
│ └─/dev/hugepages                    hugetlbfs                                    hugetlbfs  rw,relatime
├─/run                                tmpfs                                        tmpfs      rw,nosuid,nodev,mode=755
│ └─/run/user/0                       tmpfs                                        tmpfs      rw,nosuid,nodev,relatime,size=26385772k,mode=700
├─/storage/ssd3                       /dev/sda5                                    xfs        rw,relatime,attr2,inode64,usrquota,grpquota
├─/storage/ssd5                       /dev/sda7                                    xfs        rw,relatime,attr2,inode64,usrquota,grpquota
├─/boot                               /dev/sda2                                    xfs        rw,relatime,attr2,inode64,noquota
│ └─/boot/efi                         /dev/sda1                                    vfat       rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=winnt,errors=remount-ro
├─/storage/ssd4                       /dev/sda6                                    xfs        rw,relatime,attr2,inode64,usrquota,grpquota
├─/storage/ssd1                       /dev/sda3                                    xfs        rw,relatime,attr2,inode64,usrquota,grpquota
├─/storage/ssd2                       /dev/sda4                                    xfs        rw,relatime,attr2,inode64,usrquota,grpquota
├─/var/lib/nfs/rpc_pipefs             sunrpc                                       rpc_pipefs rw,relatime
└─/lxc/templates                      *hiden*.io:/lxc/templates nfs4       ro,relatime,vers=4.1,rsize=524288,wsize=524288,namlen=255,hard,proto=tcp6,timeo=600,retrans=2,sec=sys,clientaddr=*hiden*,local_lock=none,addr=*hiden*
```

And `-l trace -o` when `lxc.cgroup.cpu.shares = 100` enable.
[enabled_cpu_shares.log](https://github.com/lxc/lxc/files/6657561/enabled_cpu_shares.log)

**Comment by brauner** [comment]
Oh weird. So in the LXC log you can see that LXC check for the existence of the mountpoint `/sys/fs/cgroup/cpuacct,cpu`:
```
lxc-start 88402 20210615172933.606 TRACE    cgfsng - cgroups/cgfsng.c:__initialize_cgroups:3195 - No such file or directory - cpuacct,cpu not mounted
```
The order of `cpuacct,cpu` in that path it has taken from `/proc/<pid>/cgroup` but the actual mountpoint is reordered, i.e.
```
/sys/fs/cgroup/cpu,cpuacct
```
which is why LXC doesn't find it.

**Comment by brauner** [comment]
Oh yeah, so CentOS is weird it seems or systemd is weird on there:
```
[root@localhost ~]# cat /proc/self/cgroup
11:perf_event:/
10:pids:/
9:freezer:/
8:cpuacct,cpu:/ <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
7:memory:/
6:blkio:/
5:devices:/
4:hugetlb:/
3:net_prio,net_cls:/
2:cpuset:/
1:name=systemd:/user.slice/user-0.slice/session-c1.scope
```

and then
```
[root@localhost ~]# findmnt  | grep cpu
| | |-/sys/fs/cgroup/cpuset           cgroup        cgroup     rw,nosuid,nodev,noexec,relatime,cpuset
| | |-/sys/fs/cgroup/cpu,cpuacct      cgroup        cgroup     rw,nosuid,nodev,noexec,relatime,cpuacct,cpu
```

**Comment by Moodesstas** [comment]
Hey, I see it was merged into stable-4.0 https://github.com/lxc/lxc/blob/9265ae82df2eab0ad23a8de8248f2cdb457e10b2/src/lxc/cgroups/cgfsng.c#L3083

The problem seems to remain. Or something on our end is wrong.
```
lxc-start --version
4.0.9
```
trace log
[20210902.log](https://github.com/lxc/lxc/files/7101978/20210902.log)
